{{- with .Values.api }}
{{ $serviceName := default "api" .name}}
{{- if and .enabled .containers.envFrom}}
{{- if .containers.envFrom.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-configmap
  namespace: noah-api
data: 
  {{- range $k, $v := .containers.envFrom.configMap.data }}
  {{$k}}: {{$v}}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}
