---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: api
  namespace: default
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/helloum: glob:v*
    repository.fluxcd.io/helloum: helloum.image.repository
    tag.fluxcd.io/helloum: helloum.image.tag
spec:
  releaseName: api
  chart:
    git: git@github.com:lucas-stellet/noah-api
    path: charts/api
    ref: master
  values:
    helloum:
      image:
        repository: lustepe/simple-server-nodejs
        tag: v3
      containers:
        envFrom:
          configMap:
            data:
              MY_NAME: Lucas
    hellodois:
      image:
        repository: lustepe/simple-server-nodejs
        tag: v3
      containers:
        envFrom:
          configMap:
            data:
              MY_NAME: Noah
