---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: helloum
  namespace: numero-um
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/helloum: glob:v*
spec:
  releaseName: api
  chart:
    git: git@github.com:lucas-stellet/noah-api
    path: charts/api
    ref: master
  values:
    api:
      image:
        repository: lustepe/simple-server-nodejs
        tag: v2
      containers:
        envFrom:
          configMap:
            data:
              MY_NAME: Lucas
