{{- with .Values.v4.apiAgenda }}
{{ $serviceName := default "apiagenda" .name}}
{{- if and .enabled .containers.envFrom}}
{{- if .containers.envFrom.configMap }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ $serviceName }}-configmap
data: 
  {{- range $k, $v := .containers.envFrom.configMap.data }}
  {{$k}}: {{$v}}
  {{- end }}
{{- end }}
{{- end }}
{{- end }}clear
