api:
    enabled: true
    name: noah
    containers:
      imageName: lustepe/simple-server-nodejs:latest
      envFrom: 
        configMap:
          data:
            MY_NAME: Tatiane
      ports:
        port1:
          name: http
          containerPort: 3000
          protocol: TCP
      resources:
        limits:
          memory: 200
        requests:
          memory: 200