api:
    enabled: true
    name: noah
    containers:
      image: 
        repository: lustepe/simple-server-nodejs
        tag: v1
      envFrom: 
        configMap:
          data:
            MY_NAME: Noah
      ports:
        port1:
          name: http
          containerPort: 3000
          protocol: TCP
      resources:
        limits:
          memory: 200
        requests:
          memory: 200